models:
  name:
    - gpt-3.5-turbo-1106
    - gpt-4-1106-preview
    - Baichuan-13B-Chat
    - LLAMA-2-Chinese-13b-Chat
    - internlm-chat-7b
  embedding_api: http://10.241.132.208:28000/v1/embeddings
  chat_completion_api: http://10.241.132.208:28000/v1/chat/completions
  openai_embedding_api: https://api.openai.com/v1/embeddings
  openai_chat_completion_api: https://api.openai.com/v1/chat/completions
